# Site settings
title: "Prashanth Patil | Data Engineer Portfolio"
description: "Portfolio of Prashanth Patil, highlighting expertise in ETL, cloud platforms, data warehousing, data analysis, and data engineering projects."
baseurl: ""  # Leave empty unless your site is in a subdirectory
url: "https://github.com/PrashanthPPK/Prashanth.github.io"  # Replace with your GitHub Pages URL

# Contact info
email: prashanthpatil879@gmail.com
linkedin: https://www.linkedin.com/in/prashanthpatil879/
github: https://github.com/PrashanthPPK
location: "Guelph, ON, Canada"

# Theme settings
theme: minima  # You can change this to another GitHub Pages-supported theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown and Permalinks
markdown: kramdown
permalink: pretty

# Social links
social_links:
  github: https://github.com/PrashanthPPK
  linkedin: https://www.linkedin.com/in/prashanthpatil879/
  portfolio: https://www.novypro.com/profile_projects/prashanthpatil







